version: 2
jobs:
  test_CNNModel:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2-stretch
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/CNNModel/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            py.test -vv packages/CNNModel/tests
  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/ml_api/tests
  train_and_upload_CNNModel:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r packages/CNNModel/requirements.txt
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
            chmod +x ./scripts/fetch_kaggle_dataset.sh ./scripts/publish_model.sh
            ./scripts/fetch_kaggle_dataset.sh
            PYTHONPATH=./packages/CNNModel python3 packages/CNNModel/CNNModel/train_pipeline.py
            ./scripts/publish_model.sh ./packages/CNNModel/
workflows:
  version: 2
  test-all:
    jobs:
      - test_CNNModel
      - test_ml_api
      - train_and_upload_CNNModel
      - test_ml_api:
          requires:
            - train_and_upload_CNNModel
